### ISSUE TITLE
About sh scripts/utils/prepare_qf_ips.sh question!

### ISSUE THREAD

**Issue by ha1ha2hahaha** [LilyDaytoy/OpenPVSG#4]
When I run the "sh scripts/utils/prepare_qf_ips.sh" , only  have  62 files in the file_path "ips_val_save_qf".
Then I run the sh scripts/train/train_relation.sh, It [Errno 2] No such file or directory: '~/OpenPVSG-main/work_dirs/ips_train_save_qf/P18_02/relations.pickle'
I found  train the model some need file not  in the "ips_val_save_qf".
I want to ask would all the frames need tracking and save query features.    And the prepare_qf_ips.sh only generate 62 files. 
looking forward your reply!

**Comment by leaozhun** [comment]
Hello,have u solved this problem?I also meet it.
